from services.bot import bot
import handlers.initialization.start
import handlers.initialization.countryname_init
import handlers.initialization.capital_init
import handlers.initialization.ideology_init
import handlers.initialization.full_countryname_init
import handlers.initialization.details_init
import handlers.callbacks.callback_state_panels
import handlers.callbacks.callback_economy_panels
import handlers.callbacks.callback_spending_pamels
import handlers.callbacks.callback_territory_panels
import handlers.callbacks.callback_army_panels
import handlers.callbacks.callback_start
import handlers.callbacks.callback_initialization
import handlers.callbacks.callback_diary_panels
import handlers.callbacks.callback_end_move
import handlers.ingame_texting.loans
import handlers.ingame_texting.default_texting
import handlers.ingame_texting.country_rename
from services.constants import set_buildings, set_army_types, set_mobilization

set_buildings()
set_army_types()
set_mobilization()

bot.infinity_polling()